server {
    listen       80;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html;

    # Documento de erro, equivalente ao "error document" do S3.
    error_page 404 /error.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
